# Generated by Django 5.1.2 on 2024-11-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=20)),
                ('staffid', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.CharField(max_length=100)),
                ('dept', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('bhub', models.CharField(blank=True, max_length=100, null=True)),
                ('scenter', models.CharField(blank=True, max_length=100, null=True)),
                ('office_addr', models.CharField(default='Not Set', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('is_mgr', models.BooleanField(default=False)),
                ('reports_to', models.CharField(max_length=100)),
                ('jd_file', models.FileField(blank=True, null=True, upload_to='JD_Files/')),
                ('kpi_file', models.FileField(blank=True, null=True, upload_to='KPI_Files/')),
                ('tracker_file', models.FileField(blank=True, null=True, upload_to='Tracker_Files/')),
                ('status', models.CharField(default='Active', max_length=20)),
                ('job_div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.division')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpis', models.TextField()),
                ('weight', models.CharField(default='0', max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.job')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.region')),
            ],
        ),
        migrations.CreateModel(
            name='Scenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('bhub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.businesshub')),
            ],
        ),
    ]
