# Generated by Django 5.1.2 on 2024-11-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.job'),
        ),
    ]
