# Generated by Django 5.1.2 on 2024-11-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_month', models.CharField(max_length=2)),
                ('tr_year', models.CharField(max_length=4)),
                ('score', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='Account.staff')),
                ('kpi_items', models.ManyToManyField(to='Account.kpi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.staff')),
            ],
        ),
    ]
